return {
    NormalZones = {
        "Great White Shark", 
        "Great Hammerhead Shark", 
        "Whale Shark",
        "Isonade",
        "Forsaken Veil - Scylla",
        "Megalodon Default", 
        "Megalodon Ancient",
        "Megalodon Phantom",
        "The Kraken Pool", 
        "Ancient Kraken Pool",
        "Whales Pool",
        "MobySpawn",
        "Ancient Orcas Pool", 
        "Orcas Pool",
        "The Depths - Serpent"
    },
    EventZones = {
        "LEGO",
        "LEGO - Studolodon"
    },
    RodsNames = {
    "Ethereal Prism Rod",
    "Rod of the Zenith",
    "Challenger's Rod",
    "Leviathan's Fang Rod",
    "Volcanic Rod",
    "Heaven's Rod",
    "Crystalized Rod",
    "Ice Warpers Rod",
    "Summit Rod",
    "Arctic Rod",
    "Avalanche Rod",
    "Training Rod",
    "Plastic Rod",
    "Carbon Rod",
    "Fast Rod",
    "Lucky Rod",
    "Steady Rod",
    "Nocturnal Rod",
    "Fortune Rod",
    "Rapid Rod",
    "Magnet Rod",
    "Reinforced Rod",
    "Scurvy Rod",
    "Aurora Rod",
    "King’s Rod",
    "Trident Rod",
    "Destiny Rod",
    "Rod of The Depths"
    }
}
